# Use the official Python image from Docker Hub
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

RUN apt-get update & apt-get install -y \
    build-essential \
    gcc \ 
    libz4-dev \
    && rm-rf /var/lib/apt/lists/*

# Install Poetry
RUN pip install poetry 

# Copy the Poetry configuration files
COPY pyproject.toml poetry.lock*  /app/

# Install dependencies
RUN poetry install --no-root

# Copy the rest of your application code
COPY ./app/

# Expose the port of your application runs on
EXPOSE 5000

# Command to run the FastAPI application
CMD ['poetry', 'run', 'uvicorn', 'app.server:app', '--host', '0.0.0.0', '--reload', '--port', '5000']